# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.4
fabric_version=0.140.2+1.21.11

# Mod Properties
mod_version=1.6.1+1.21.11
maven_group=com.itsjustmiaouss
archives_base_name=ijmtweaks

# Dependencies
minecraft_min=1.21.11
fabric_api_min=0.140.2+1.21.11

mod_menu=17.0.0-beta.1
yacl=3.8.1+1.21.11-fabric
fabrishot=1.16.4